### PR TITLE
[aws-endpoint]: Be able to set a custom endpoint for use another AWS compatible cloud

### PR DESCRIPTION
**Pull request by sanmibuh**
#12

### CODE REVIEW

**Comment by peter-thomas-mgd** [comment]
Your changes look relatively straightforward, so I am comfortable with the implementation approach.

Ideally I'd also like to include an integration test for this use case to ensure that this option continues to work reliably as the code evolves. It looks like there is GitHub Actions support for LocalStack, but it I am not familiar with it. The example in the documentation only shows CLI level integration, so I don't know whether we could configure the Java API-based tests to work with it. Maybe this is something that's done using environment variables? Have you set this up with any of your projects in the past?

**Comment by sanmibuh** [comment]
I have done this integration test in other projects with test containers and it's very simple (in a Java Springboot project)

I could investigate how to do it on a Gradle Plugin Test and create another PR (or use the same adding the test)

Local stack is 100% compatible with AWS S3 api, so you could use the same code.

In this case, you could use the local stack for all tests.

**Comment by sanmibuh** [comment]
Hi @peter-thomas-mgd 
You have already the tests with localstack and test containers. 
It runs locally without any external configuration. Test containers generates the url and credentials dynamically and iI inject then when those data are needed.

The tests are not using a real S3 account anymore :)

**Comment by peter-thomas-mgd** [comment]
Looks good! Thanks for working on this. I'm going to incorporate this into a new release when I get some cycles over the next day or so.

**Pull request merged**
